M48
; DRILL file {KiCad 7.0.5-7.0.5~ubuntu22.04.1} date Sat 24 Jun 2023 11:50:11 AM CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-24T11:50:11+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-7.0.5~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.700
%
G90
G05
T1
X104.11Y-103.38
X109.89Y-103.38
T2
X118.837Y-145.4
X118.837Y-152.4
T0
M30
