M48
; DRILL file {KiCad 7.0.2-6a45011f42~172~ubuntu22.04.1} date Tue 25 Apr 2023 08:16:26 PM CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-25T20:16:26+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-6a45011f42~172~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.700
%
G90
G05
T1
X104.11Y-103.38
X109.89Y-103.38
T2
X118.837Y-145.4
X118.837Y-152.4
T0
M30
