M48
; DRILL file {KiCad 7.0.0} date Tue 28 Feb 2023 11:08:12 PM CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-28T23:08:12+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.700
%
G90
G05
T1
X104.11Y-103.38
X109.89Y-103.38
T2
X118.837Y-145.4
X118.837Y-152.4
T0
M30
